name: Build and publish to npm
on:
  push:
    branches:
      - master
jobs:
  check:
    name: Check if version changed
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master
      - name: Set up Node.js
        uses: actions/setup-node@master
        with:
          node-version: 10.19.0
      - name: Check version
        id: check # This will be the reference for getting the outputs.
        uses: EndBug/version-check@v1 # You can choose the version/branch you prefer.
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          file-url: https://www.npmjs.com/package/@makesenseorg/design-system
          static-checking: localIsNew
      - name: Version is unchanged
        if: steps.check.outputs.changed != 'true'
        run: 'echo "No version change in package.json :/"'
  publish:
    needs: check
    if: needs.check.outputs.changed == 'true'
    name: Build and publish to npm
    runs-on: ubuntu-latest
    steps:
      - name: Create tag
        run: |
          git tag -a v${{needs.job1.outputs.version}}
          git push origin v${{needs.job1.outputs.version}}

      - name: Install dependencies
        run: yarn install

      - name: Publish to npm
        run: yarn publish --non-interactive --new-version ${{needs.job1.outputs.version}}
